# Generated by Django 5.1.4 on 2026-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_team_teaminvitation_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
