# Generated by Django 5.1.4 on 2026-06-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_userupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("link", models.URLField(blank=True)),
                ("guests", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#DBEAFE", max_length=7)),
                ("external_provider", models.CharField(blank=True, max_length=40)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start", "created_at"],
                "indexes": [
                    models.Index(fields=["owner", "start"], name="projects_ca_owner_i_a7253b_idx"),
                    models.Index(fields=["external_provider", "external_id"], name="projects_ca_externa_144e49_idx"),
                ],
            },
        ),
    ]
