# Generated by Django 5.1.4 on 2026-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="total_steps",
            field=models.IntegerField(default=0),
        ),
    ]
