# Generated by Django 5.1.4 on 2026-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_task_category_task_duration_task_notes_task_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
