import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "../contexts/UserContext";
import { ProjectsProvider } from "../contexts/ProjectsContext";
import { ThemeProvider } from "../contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <UserProvider>
            <ProjectsProvider>
              {children}
            </ProjectsProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
